bind :53
cache-size 30000
prefetch-domain yes
serve-expired yes
serve-expired-ttl 86400

speed-check-mode ping,tcp:443
speed-check-thread 6
speed-check-timeout 400

server 1.1.1.1
server 1.0.0.1
server 8.8.8.8
server 8.8.4.4
server 9.9.9.9
server 168.63.129.16
server 40.90.4.1

server /xbox.com/1.1.1.1
server /xboxlive.com/1.1.1.1
server /xboxservices.com/1.1.1.1
server /microsoft.com/1.1.1.1
server /login.live.com/1.1.1.1
server /account.microsoft.com/1.1.1.1
server /msedge.net/1.1.1.1
server /aka.ms/1.1.1.1

server /storeedgefd.dsx.mp.microsoft.com/8.8.8.8
server /assets1.xboxlive.com/8.8.8.8
server /assets2.xboxlive.com/8.8.8.8

domain-rules /xbox.com/microsoft/
domain-rules /xboxlive.com/microsoft/
domain-rules /xboxservices.com/microsoft/
domain-rules /live.com/microsoft/
domain-rules /login.live.com/microsoft/
domain-rules /account.microsoft.com/microsoft/
domain-rules /microsoft.com/microsoft/
domain-rules /msedge.net/microsoft/
domain-rules /aka.ms/microsoft/
domain-rules /msftconnecttest.com/microsoft/

no-resolv
force-AAAA-SOA yes
force-qtype-SOA yes
dualstack-ip-selection yes
